import React, { useEffect, useMemo, useState } from 'react';
import { Search, Bell, Settings, FlaskConical, Compass, Lightbulb, TrendingUp, Cog, ChevronDown, Megaphone, CheckCircle2, FileText, X } from 'lucide-react';

const filtersConfig = {
  'Product Category': ['Composite foods', 'Fat and sauces', 'Fish Meat Eggs', 'Prepared meals', 'Snacks'],
  'Food Group': ['Dressings and sauces', 'Eggs', 'Pizza pies and quiches', 'Processed meat', 'Sandwiches', 'Soups', 'Sweet bakery products'],
  'Labelling/Claims': ['Fat Free', 'High Fibre', 'High Protein', 'Keto-friendly', 'Low Carb', 'Low Sugar', 'No Added Sugar', 'Organic', 'Vegan', 'Gluten Free', 'Clean Label'],
  Allergens: ['allergen free', 'celery', 'eggs', 'fish', 'gluten', 'milk', 'mustard', 'nuts', 'soy'],
  Flavour: ['bbq', 'cheesy/creamy', 'citrus', 'fruity', 'garlic/onion', 'herby', 'mediterranean style', 'salty', 'sour/tangy', 'spicy', 'sweet/savoury'],
  Ingredient: ['almond', 'apple', 'barley', 'beef', 'calcium carbonate', 'citric acid', 'garlic', 'mozzarella', 'paprika', 'yeast']
};

const products = [
  item('Apple Pie','Composite foods','Sweet bakery products',['Clean Label'],['eggs','gluten','milk','nuts'],['sweet/savoury','fruity'],['apple','almond'],'3 Fellers','Apples, sugar, white rice flour, walnuts, butter, eggs, tapioca flour, cornstarch.'),
  item('Pumpkin Pie','Composite foods','Sweet bakery products',['Clean Label'],['eggs','gluten','milk'],['sweet/savoury','spicy'],['calcium carbonate'],'3 Fellers','Pumpkin, condensed milk, butter, eggs, white rice flour, tapioca powder, sugar.'),
  item('365 everyday value, chicken & bbq sauce mini pizzas','Composite foods','Pizza pies and quiches',['Organic'],['gluten','milk'],['bbq','garlic/onion'],['garlic','paprika','yeast'],'365 Everyday Value','Organic crust, wheat flour, organic wheat germ, evaporated cane sugar, olive oil.'),
  item('365 everyday value, mini pizzas, three cheese','Composite foods','Pizza pies and quiches',['Organic'],['gluten','milk'],['cheesy/creamy','garlic/onion'],['mozzarella','yeast'],'365 Everyday Value','Unbleached wheat flour, water, canola oil, yeast, salt, mozzarella, tomato sauce.'),
  item('Mediterranean Style Pizza','Composite foods','Pizza pies and quiches',['High Fibre'],['gluten','milk'],['mediterranean style','herby'],['garlic','paprika'],'365 Whole Foods Market','Whole grain wheat flour, filtered water, flax, olive oil, sunflower oil, sea salt.'),
  item('Thin Crust Pepperoni Pizza','Composite foods','Pizza pies and quiches',['High Protein'],['gluten','milk'],['spicy','garlic/onion'],['beef','paprika','yeast'],'365 Whole Foods Market','Wheat flour, tomato sauce, mozzarella, pepperoni, yeast, paprika, garlic.'),
  item('Cauliflower crust cheese pizza','Composite foods','Pizza pies and quiches',['Gluten Free','Low Carb'],['milk'],['cheesy/creamy'],['mozzarella'],'365 Whole Foods Market','Cauliflower crust, chickpea flour, mozzarella, tomato sauce, rice flour, basil.'),
  item('BBQ chicken pizza','Composite foods','Pizza pies and quiches',['High Protein'],['gluten','milk'],['bbq','spicy'],['paprika','garlic'],"By Sainsbury's",'Fortified wheat flour, BBQ chicken, tomato puree, vinegar, onion powder, paprika.'),
  item('Chipotle Salsa','Fat and sauces','Dressings and sauces',['Vegan','Low Sugar'],['allergen free'],['spicy','garlic/onion'],['garlic','citric acid'],'100% Salsa','Chipotle peppers, tomatoes, onions, garlic cloves, kosher salt, citric acid.'),
  item('Vegan Garlic Aioli','Fat and sauces','Dressings and sauces',['Vegan','Clean Label'],['mustard'],['garlic/onion','cheesy/creamy'],['garlic'],'Plant Pantry','Rapeseed oil, aquafaba, garlic puree, mustard, lemon juice, sea salt.'),
  item('Tuna Sandwich','Composite foods','Sandwiches',['High Protein'],['fish','gluten','eggs'],['salty','sour/tangy'],['barley'],'18th Street Deli','Wheat bread, tuna, mayonnaise, celery, lemon juice, salt, black pepper.'),
  item('Organic Lentil Soup','Prepared meals','Soups',['Organic','Vegan','High Fibre'],['celery'],['herby','mediterranean style'],['garlic'],'365 Everyday Value','Water, green lentils, celery, onion, garlic, tomato puree, olive oil, parsley.'),
  item('Keto Egg Bites','Fish Meat Eggs','Eggs',['Keto-friendly','Low Carb','High Protein'],['eggs','milk'],['cheesy/creamy'],['mozzarella'],'Morning Kitchen','Whole eggs, cottage cheese, mozzarella, cream, sea salt, black pepper.')
];

function item(name, category, group, claims, allergens, flavours, ingredients, brand, list) {
  return { name, category, group, claims, allergens, flavours, ingredients, brand, list };
}
function keyOf(value) { return String(value || '').toLowerCase().replace(/[^a-z0-9]/g, ''); }
function makeConcept(product, id) {
  return { id: 'CPT-' + id, name: product.name, brand: product.brand, category: product.category, group: product.group, claims: product.claims || [], allergens: product.allergens || [], flavours: product.flavours || [], ingredients: product.ingredients || [], list: product.list, source: product.source || 'Market product', status: product.status || 'Draft', risk: product.risk || ((product.allergens || []).length > 2 ? 'Medium' : 'Low'), lastEdited: product.lastEdited || 'Today', duplicateKey: keyOf(product.name) };
}
const seedConcepts = [
  makeConcept({ name:'Spicy Honey Garlic Glaze', brand:'GlazeCrafters', category:'Fat and sauces', group:'Dressings and sauces', claims:['Clean Label','High Protein'], allergens:['soy'], flavours:['spicy','garlic/onion'], ingredients:['garlic','paprika'], list:'Honey, soy sauce, garlic, chilli paste, vinegar, salt.', source:'AI concept', status:'Draft', risk:'Medium' }, 1029),
  makeConcept({ name:'Umami Onion Snack Mix', brand:'Snack Masters', category:'Snacks', group:'Processed meat', claims:['Clean Label'], allergens:['gluten','soy'], flavours:['garlic/onion','salty'], ingredients:['yeast','garlic'], list:'Rice crackers, cashews, roasted onion powder, yeast extract, sunflower oil.', source:'AI concept', status:'Review', risk:'Low' }, 1104),
  makeConcept({ name:'Citrus Paprika Rub', brand:'Spice & Co', category:'Fat and sauces', group:'Dressings and sauces', claims:['Low Sugar','Vegan'], allergens:['allergen free'], flavours:['citrus','spicy'], ingredients:['paprika','citric acid'], list:'Smoked paprika, sea salt, black pepper, dried orange peel, coriander, citric acid.', source:'AI concept', status:'Ready', risk:'Medium' }, 1188)
];
const nav = [['explore','Explore',Compass], ['concepts','Concepts',Lightbulb], ['risk','Launch Risk',TrendingUp], ['configure','Configure',Cog]];

export default function App() {
  const [screen, setScreen] = useState('login');
  const [concepts, setConcepts] = useState(seedConcepts);
  const addProductsToShortlist = (selected) => {
    let added = 0;
    setConcepts((current) => {
      const used = new Set(current.map((concept) => concept.duplicateKey));
      const next = [...current];
      selected.forEach((product, index) => {
        const key = keyOf(product.name);
        if (!used.has(key)) { next.unshift(makeConcept(product, 1300 + current.length + index)); used.add(key); added += 1; }
      });
      return next;
    });
    return added;
  };
  if (screen === 'login') return <><Login onLogin={() => setScreen('explore')} /><style>{css}</style></>;
  return <div className="app"><Header onSignOut={() => setScreen('login')} /><Sidebar screen={screen} setScreen={setScreen} /><main className="content">{screen === 'explore' && <Explore concepts={concepts} onAdd={addProductsToShortlist} onView={() => setScreen('concepts')} />}{screen === 'concepts' && <Concepts concepts={concepts} setConcepts={setConcepts} />}{screen === 'risk' && <Risk />}{screen === 'configure' && <Configure />}</main><style>{css}</style></div>;
}

function Login({ onLogin }) {
  return <main className="loginPage"><section className="loginCard"><div className="loginBody"><h2>Platform</h2><h1>Log in to your account</h1><p>Enter your credentials to access your workspace.</p><form onSubmit={(event) => { event.preventDefault(); onLogin(); }}><label>Email address<input placeholder="name@company.com" /></label><label>Password<input type="password" placeholder="Enter your password" /></label><button>Log in</button><div className="loginRow"><label><input type="checkbox" /> Remember me</label><a>Forgot password?</a></div></form></div><footer><b>New to Platform?</b><button>Create account</button></footer></section></main>;
}
function Header({ onSignOut }) {
  const [open, setOpen] = useState(false);
  return <header className="topbar"><span className="logo"><FlaskConical size={16} /></span><b>Food Innovate</b><div className="actions"><Search size={18} /><Bell size={18} /><Settings size={18} /><div className="avatarWrap"><button className="avatar" onClick={() => setOpen(!open)}>SC</button>{open && <div className="menu"><b>Sarah Chen</b><small>Food Innovate workspace</small><button onClick={onSignOut}>Sign out</button></div>}</div></div></header>;
}
function Sidebar({ screen, setScreen }) {
  return <aside className="sidebar">{nav.map(([id, label, Icon]) => <button key={id} className={screen === id ? 'active' : ''} onClick={() => setScreen(id)}><Icon size={18} /><span>{label}</span></button>)}</aside>;
}

function Explore({ concepts, onAdd, onView }) {
  const [open, setOpen] = useState(null);
  const [timeframe, setTimeframe] = useState('1 Year');
  const [selected, setSelected] = useState([]);
  const [notice, setNotice] = useState('');
  const [filters, setFilters] = useState({ 'Product Category': [], 'Food Group': [], 'Labelling/Claims': [], Allergens: [], Flavour: [], Ingredient: [] });
  useEffect(() => { if (!notice) return undefined; const timer = setTimeout(() => setNotice(''), 3500); return () => clearTimeout(timer); }, [notice]);
  const rows = useMemo(() => products.filter((product) => matchProduct(product, filters)), [filters]);
  const factor = { '1 Month': 0.18, '3 Months': 0.36, '6 Months': 0.62, '1 Year': 1, 'All Time': 1.35 }[timeframe];
  const shortlisted = new Set(concepts.map((concept) => concept.duplicateKey));
  const updateFilter = (label, value) => setFilters((current) => ({ ...current, [label]: value }));
  const add = () => { const count = onAdd(selected); setSelected([]); setNotice(count ? count + ' product' + (count === 1 ? '' : 's') + ' added to Concept Shortlist.' : 'Selected products are already shortlisted.'); };
  return <div>{notice && <Notice text={notice} onView={onView} onClose={() => setNotice('')} />}<div className="filters">{Object.keys(filtersConfig).map((label) => <MultiFilter key={label} label={label} options={filtersConfig[label]} selected={filters[label]} open={open === label} setOpen={() => setOpen(open === label ? null : label)} onChange={(value) => updateFilter(label, value)} />)}</div><div className="exploreSplit"><section className="exploreLeft"><div className="leftTop"><aside className="left"><Timeframe value={timeframe} onChange={setTimeframe} /><Stat title="Number of Products" value={(rows.length ? Math.round((rows.length * 18347 + 5121) * factor) : 0).toLocaleString()} /><Stat title="Number of Brands" value={(rows.length ? Math.max(Math.round(rows.length * 37 * factor), 12) : 0).toLocaleString()} /></aside><Trend title="Trending Flavours" label="Flavour" rows={trend(rows, 'flavours', factor)} /><Trend title="Trending Ingredients" label="Ingredient" rows={trend(rows, 'ingredients', factor)} /></div><Pricing rows={priceRows(rows, factor)} /></section><Market rows={rows} selected={selected} setSelected={setSelected} onAdd={add} shortlisted={shortlisted} /></div></div>;
}
function Notice({ text, onView, onClose }) { return <div className="shortlistNotice"><span>{text}</span><div className="noticeActions"><button onClick={onView}>View shortlist</button><button className="noticeClose" onClick={onClose}>x</button></div></div>; }
function matchProduct(product, filters) { const any = (selected, values) => !selected.length || selected.some((value) => values.includes(value)); return any(filters['Product Category'], [product.category]) && any(filters['Food Group'], [product.group]) && any(filters['Labelling/Claims'], product.claims) && any(filters.Allergens, product.allergens) && any(filters.Flavour, product.flavours) && any(filters.Ingredient, product.ingredients); }
function trend(rows, key, factor) { const counts = new Map(); rows.forEach((product) => product[key].forEach((value) => counts.set(value, (counts.get(value) || 0) + 1))); const output = [...counts.entries()].sort((a, b) => b[1] - a[1]).slice(0, 10).map(([name, count], index) => [name, '+' + (count * 7.4 * factor + (10 - index) * 0.4).toFixed(2) + '%', 'up']); return output.length ? output : [['No matching data', '0.0%', 'flat']]; }
function priceRows(rows, factor) { const used = new Set(rows.flatMap((product) => product.ingredients)); const base = [['almond','$22.03',3.24],['apple','$1.75',7.57],['barley','$0.65',-25.57],['beef','$20.28',36.42],['citric acid','$1.08',4.4],['garlic','$4.50',12.4],['mozzarella','$3.90',6.2],['paprika','$4.15',2.2],['yeast','$15.30',8.7]]; return (base.filter((row) => used.has(row[0])).length ? base.filter((row) => used.has(row[0])) : base).map(([name, price, growth]) => [name, price, growth * factor]).sort((a, b) => b[2] - a[2]).map(([name, price, growth]) => [name, price, (growth >= 0 ? '+' : '') + growth.toFixed(2) + '%', growth]); }
function priceClass(value) { if (value < 0) return 'price-fall'; if (value <= 5) return 'price-warn'; return 'price-risk'; }

function MultiFilter({ label, options, selected, open, setOpen, onChange }) {
  const [query, setQuery] = useState('');
  const [showSelected, setShowSelected] = useState(false);
  const all = selected.length === options.length;
  const visible = options.filter((option) => option.toLowerCase().includes(query.toLowerCase()) && (!showSelected || selected.includes(option)));
  const summary = !selected.length ? 'All' : selected.length === 1 ? selected[0] : selected.slice(0, 2).join(', ') + '...';
  const toggle = (option) => onChange(selected.includes(option) ? selected.filter((item) => item !== option) : [...selected, option]);
  return <div className={'filter ' + (open ? 'open' : '')}><div className="filterTitle"><span>{label}</span><button>...</button></div><button className="trigger" onClick={setOpen}><span>{summary}</span><ChevronDown size={16} /></button>{open && <div className="dropdown"><div className="searchBox"><input placeholder="Search value" value={query} onChange={(event) => setQuery(event.target.value)} /><Search size={16} /></div><label className="opt all"><input type="checkbox" checked={all} onChange={() => onChange(all ? [] : [...options])} /> Select all</label><div className="optList">{visible.map((option) => <label className="opt" key={option}><input type="checkbox" checked={selected.includes(option)} onChange={() => toggle(option)} /> {option}</label>)}</div><label className="switch"><input type="checkbox" checked={showSelected} onChange={(event) => setShowSelected(event.target.checked)} /><span /> Show selected</label></div>}</div>;
}
function Timeframe({ value, onChange }) { return <section className="card timeframe"><h3>Timeframe</h3>{['1 Month','3 Months','6 Months','1 Year','All Time'].map((option) => <label key={option} className={value === option ? 'selected' : ''}><input type="radio" name="timeframe" checked={value === option} onChange={() => onChange(option)} /> {option}</label>)}</section>; }
function Stat({ title, value }) { return <section className="stat"><span>{title}</span><strong>{value}</strong></section>; }
function Trend({ title, label, rows }) { return <section className="card trend"><h3>{title}</h3><table><thead><tr><th>{label}</th><th>Growth %</th></tr></thead><tbody>{rows.map((row) => <tr key={row[0]}><td>{row[0]}</td><td className={row[2]}>{row[1]}</td></tr>)}</tbody></table></section>; }
function Pricing({ rows }) { return <section className="card pricing"><h3>Ingredient Pricing</h3><p>NOTE: Pricing based off the latest 2025 data. Sorted by price growth.</p><table><thead><tr><th>Ingredient</th><th>Price (USD)</th><th>Growth %</th></tr></thead><tbody>{rows.map((row) => <tr key={row[0]}><td>{row[0]}</td><td>{row[1]}</td><td className={priceClass(row[3])}>{row[2]}</td></tr>)}</tbody></table></section>; }
function Market({ rows, selected, setSelected, onAdd, shortlisted }) { const names = new Set(selected.map((product) => product.name)); const toggle = (product) => setSelected((current) => current.some((item) => item.name === product.name) ? current.filter((item) => item.name !== product.name) : [...current, product]); return <section className="card market"><h3>Similar Products on the Market</h3>{selected.length > 0 && <div className="selectionBar"><b>{selected.length} selected</b><button onClick={() => setSelected([])}>Clear</button><button className="primaryMini" onClick={onAdd}>Add to Concept Shortlist</button></div>}{rows.length ? <table><thead><tr><th className="selectCol"></th><th className="statusCol"></th><th>Product Name</th><th>Ingredient List</th><th>Brand</th></tr></thead><tbody>{rows.map((product) => { const already = shortlisted.has(keyOf(product.name)); const checked = names.has(product.name) || already; return <tr key={product.name} className={checked ? 'rowSelected' : ''}><td className="selectCol"><input type="checkbox" checked={checked} disabled={already} onChange={() => toggle(product)} /></td><td className="statusCol">{already && <CheckCircle2 size={16} />}</td><td><a>{product.name}</a>{already && <em>Shortlisted</em>}</td><td>{product.list}</td><td><b>{product.brand}</b></td></tr>; })}</tbody></table> : <div className="empty"><b>No data</b><span>There was no data found for the current filters.</span></div>}</section>; }

function Concepts({ concepts, setConcepts }) {
  const [query, setQuery] = useState('');
  const [status, setStatus] = useState('All statuses');
  const [sort, setSort] = useState({ key: 'id', dir: 'desc' });
  const [selected, setSelected] = useState([]);
  const [openConcept, setOpenConcept] = useState(null);
  const value = (concept, key) => key === 'risk' ? ({ High: 3, Medium: 2, Low: 1 }[concept.risk] || 0) : ({ id: concept.id, name: concept.name, status: concept.status, source: concept.source, category: concept.group, claims: concept.claims.join(', '), edited: concept.lastEdited }[key] || '');
  const rows = useMemo(() => { const q = query.toLowerCase(); return concepts.filter((concept) => (status === 'All statuses' || concept.status === status) && (!q || [concept.name, concept.brand, concept.category, concept.group, concept.list, ...concept.claims, ...concept.ingredients].join(' ').toLowerCase().includes(q))).sort((a, b) => { const av = value(a, sort.key); const bv = value(b, sort.key); const result = typeof av === 'number' && typeof bv === 'number' ? av - bv : String(av).localeCompare(String(bv)); return sort.dir === 'asc' ? result : -result; }); }, [concepts, query, status, sort]);
  const head = (label, key) => <th><button className="sortHeader" onClick={() => setSort((current) => current.key === key ? { key, dir: current.dir === 'asc' ? 'desc' : 'asc' } : { key, dir: 'asc' })}>{label}<span>{sort.key === key ? sort.dir : 'sort'}</span></button></th>;
  const toggle = (id) => setSelected((current) => current.includes(id) ? current.filter((item) => item !== id) : [...current, id]);
  const clear = () => setSelected([]);
  const deleteSelected = () => { setConcepts((current) => current.filter((item) => !selected.includes(item.id))); clear(); };
  const duplicateSelected = () => { setConcepts((current) => [...current.filter((item) => selected.includes(item.id)).map((item, index) => ({ ...item, id: 'CPT-D' + (Date.now() + index).toString().slice(-5), name: item.name + ' copy', status: 'Draft', duplicateKey: item.duplicateKey + 'copy' + index })), ...current]); clear(); };
  return <div className="conceptsPage"><div className="pageTitle"><h1>Concept Shortlist</h1><p>Search, filter, manage and edit shortlisted concepts.</p></div><section className="conceptLibrary"><div className="conceptToolbar"><div className="conceptSearch"><Search size={16} /><input placeholder="Search concepts, brands, ingredients..." value={query} onChange={(event) => setQuery(event.target.value)} />{query && <button className="conceptSearchClear" onClick={() => setQuery('')}><X size={14} /></button>}</div><select value={status} onChange={(event) => setStatus(event.target.value)}><option>All statuses</option><option>Draft</option><option>Review</option><option>Ready</option></select></div>{selected.length > 0 && <div className="bulkBar"><b>{selected.length} selected</b><div className="bulkActions"><button onClick={duplicateSelected}>Duplicate</button><button onClick={deleteSelected}>Delete</button><button onClick={clear}>Clear</button></div><button className="reportAction">Generate report <FileText size={14} /></button></div>}<table className="conceptTable"><thead><tr><th className="selectCol"></th>{head('Name','name')}{head('Status','status')}{head('Source','source')}{head('Category','category')}{head('Claims','claims')}{head('Risk','risk')}{head('Last edited','edited')}</tr></thead><tbody>{rows.map((concept) => <tr key={concept.id} className={selected.includes(concept.id) ? 'rowSelected' : ''}><td className="selectCol"><input type="checkbox" checked={selected.includes(concept.id)} onChange={() => toggle(concept.id)} /></td><td><button className="conceptName" onClick={() => setOpenConcept(concept)}>{concept.name}</button><small>{concept.brand}</small></td><td><span className={'badge status' + concept.status}>{concept.status}</span></td><td><span className="badge sourceBadge">{concept.source}</span></td><td>{concept.group}</td><td>{concept.claims.slice(0, 2).join(', ') || '-'}</td><td><span className={'riskBadge risk' + concept.risk}>{concept.risk}</span></td><td>{concept.lastEdited}</td></tr>)}</tbody></table></section>{openConcept && <ConceptDrawer concept={openConcept} onClose={() => setOpenConcept(null)} setConcepts={setConcepts} />}</div>;
}
function ConceptDrawer({ concept, onClose, setConcepts }) { const [draft, setDraft] = useState(concept); const save = () => { setConcepts((current) => current.map((item) => item.id === concept.id ? { ...draft, lastEdited: 'Just now' } : item)); onClose(); }; return <aside className="conceptDrawer"><div className="drawerHeader"><div><b>{concept.id}</b><h2>{draft.name}</h2></div><button onClick={onClose}>x</button></div><label>Name<input value={draft.name} onChange={(event) => setDraft({ ...draft, name: event.target.value })} /></label><label>Brand<input value={draft.brand} onChange={(event) => setDraft({ ...draft, brand: event.target.value })} /></label><label>Ingredient list<textarea value={draft.list} onChange={(event) => setDraft({ ...draft, list: event.target.value })} /></label><div className="drawerMeta"><span>{draft.category}</span><span>{draft.group}</span><span>{draft.risk} risk</span></div><h3>Claims</h3><p>{draft.claims.join(', ') || 'No claims'}</p><h3>Allergens</h3><p>{draft.allergens.join(', ') || 'No allergens'}</p><footer><button onClick={onClose}>Cancel</button><button className="primary" onClick={save}>Save changes</button></footer></aside>; }
function Risk() { return <div className="riskPage"><h1>Launch Risk Intelligence</h1><p>Curated weekly risk briefings by our industry experts.</p><section className="brief"><h2><Megaphone size={20} /> Weekly Expert Summary</h2><blockquote>We're seeing significant volatility in key spice commodities heading into Q3, while regulatory bodies in the EU are tightening clean label definitions.</blockquote><div className="briefGrid"><div><h3 className="down">Supply & Cost Risks</h3><p><b>Paprika & Capsicum</b><br />Spot prices have surged 18% in the last 14 days.</p><p><b>Glass Packaging</b><br />Manufacturers are signaling a potential 5% price increase.</p></div><div><h3 className="up">Easing Pressures</h3><p><b>Soy Oil</b><br />Record harvests have stabilized emulsifier costs.</p><p><b>Logistics</b><br />Port congestion has eased in major Asian hubs.</p></div></div></section></div>; }
function Configure() { return <div className="config"><h1>System Configuration</h1><p>Set up your company profile to tailor trends, AI prompts, and market signals.</p><section className="configCard"><h2>Company Profile</h2><div className="configGrid"><ConfigField label="Primary Industry / Sector" /><ConfigField label="Target Market Focus" /><ConfigField label="Brand Positioning" /><ConfigField label="Company Name" input /></div><hr /><h3>Prompt Preferences</h3>{['Prioritize Clean Label formulation in AI concepts','Focus on cost-optimized ingredients','Include experimental trends in Explore feed'].map((item, index) => <label className="toggle" key={item}><input type="checkbox" defaultChecked={index < 2} /><span /> {item}</label>)}<footer><button>Cancel</button><button className="primary">Save Configuration</button></footer></section></div>; }
function ConfigField({ label, input }) { const values = { 'Primary Industry / Sector': ['Sauces & Condiments','Snacks & Bakery','Dairy & Alternatives','Ready Meals','Plant-Based Foods','Beverages','Confectionery','Meat, Fish & Eggs'], 'Target Market Focus': ['Global','United Kingdom','Europe','North America','Asia Pacific','Premium Retail','Foodservice','Private Label'], 'Brand Positioning': ['Value','Mainstream','Premium','Health-led','Clean Label','Sustainable','Indulgent','Functional Nutrition'] }; if (input) return <label className="field"><span>{label}</span><input placeholder="Global Taste Innovations" /></label>; return <label className="field"><span>{label}</span><select defaultValue=""><option value="" disabled>Select option</option>{(values[label] || []).map((option) => <option key={option}>{option}</option>)}</select></label>; }

const css = [
  ':root{--blue-500:#2462FF;--blue-700:#0E4EEE;--lavender-50:#F3F2FF;--ink-900:#27272D;--ink-600:#5D5E6A;--ink-400:#9B9CA6;--red-600:#D32F2F;--orange-600:#ED6C02;--green-700:#2E7D32;--border:rgba(39,39,45,.08);--border-2:#DEDDEE;--muted-blue:rgba(36,98,255,.10);--shadow:0 1px 3px rgba(39,39,45,.08);--shadow-menu:0 16px 40px rgba(39,39,45,.14);--font-xs:11px;--font-sm:12px;--font-md:13px;--font-base:14px;--font-lg:16px;--font-xl:20px;--font-2xl:24px;--font-3xl:30px;--weight-medium:650;--weight-semibold:750;--weight-bold:850}',
  '*{box-sizing:border-box}html,body{margin:0;min-height:100%;font-family:Inter,Roboto,Arial,sans-serif;color:var(--ink-900);background:var(--lavender-50);font-size:14px;line-height:1.45;font-weight:500;letter-spacing:-.01em}button,input,select,textarea{font:inherit}button{cursor:pointer}.app{min-height:100vh;background:var(--lavender-50)}.content{margin-left:78px;padding:24px 24px 48px}.card,.brief,.configCard,.conceptLibrary,.stat{background:#fff;border:1px solid var(--border);border-radius:14px;box-shadow:var(--shadow);overflow:hidden}.card h3,.brief h2,.configCard h2{font-size:16px;line-height:24px;margin:0;padding:16px 18px;font-weight:750}.pageTitle{margin:4px 0 20px}.pageTitle h1,.riskPage h1,.config h1{margin:0;font-size:24px;line-height:32px;font-weight:850}.pageTitle p,.riskPage>p,.config>p{color:var(--ink-400);margin:6px 0 20px}',
  '.topbar{height:56px;display:flex;align-items:center;gap:12px;padding:0 20px;border-bottom:1px solid var(--border);background:rgba(255,255,255,.92);position:sticky;top:0;z-index:1000}.logo,.avatar{width:34px;height:34px;border-radius:999px;background:var(--muted-blue);color:var(--blue-500);display:grid;place-items:center;border:1px solid rgba(36,98,255,.12)}.topbar>b{font-size:16px;font-weight:750}.actions{margin-left:auto;display:flex;align-items:center;gap:18px;color:var(--ink-600)}.avatar{font-size:12px;font-weight:850}.avatarWrap{position:relative}.menu{position:absolute;right:0;top:44px;width:260px;background:#fff;border:1px solid var(--border);border-radius:8px;box-shadow:var(--shadow-menu);padding:14px;z-index:2000}.menu small{display:block;color:var(--ink-400);margin:4px 0 12px;font-size:12px}.menu button{width:100%;height:40px;border:0;border-radius:8px;background:var(--lavender-50);font-weight:750;text-align:left;padding:0 12px}.sidebar{position:fixed;top:56px;left:0;bottom:0;width:78px;border-right:1px solid var(--border);background:rgba(255,255,255,.86);padding:20px 8px;display:flex;flex-direction:column;gap:12px}.sidebar button{border:0;background:transparent;border-radius:12px;color:var(--ink-400);min-height:58px;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:5px;font-size:11px;font-weight:750}.sidebar .active{background:var(--muted-blue);color:var(--blue-500)}',
  '.filters{display:grid;grid-template-columns:repeat(6,minmax(0,1fr));gap:14px;margin-bottom:22px;position:relative;z-index:100}.filter{position:relative;background:#fff;border:1px solid var(--border);border-radius:8px;padding:14px;box-shadow:var(--shadow)}.filter.open{box-shadow:0 0 0 3px rgba(36,98,255,.18),var(--shadow)}.filterTitle{display:flex;justify-content:space-between;align-items:center;margin-bottom:10px}.filterTitle span,th{font-size:11px;text-transform:uppercase;letter-spacing:.08em;font-weight:850;color:var(--ink-400)}.filterTitle button,.trigger,.searchBox,.conceptSearch,.conceptToolbar select,.field input,.field select,.conceptDrawer input,.conceptDrawer textarea{border:1px solid var(--border-2);border-radius:8px;background:#fff}.filterTitle button{width:30px;height:30px;color:var(--ink-400)}.trigger{width:100%;height:44px;display:flex;align-items:center;justify-content:space-between;padding:0 12px;color:var(--ink-900)}.trigger span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.dropdown{position:absolute;top:calc(100% + 6px);left:10px;width:min(320px,calc(100vw - 120px));background:#fff;border:1px solid var(--border);border-radius:6px;box-shadow:var(--shadow-menu);padding:10px;z-index:500}.filter:nth-child(n+5) .dropdown{left:auto;right:10px}.searchBox{height:40px;display:flex;align-items:center;padding:0 10px;margin-bottom:8px}.searchBox input,.conceptSearch input{border:0;outline:0;width:100%}.optList{max-height:250px;overflow:auto}.opt{display:flex;align-items:center;gap:10px;min-height:34px;font-weight:650;color:var(--ink-600)}.opt input,.timeframe input{accent-color:var(--blue-500)}.all{border-bottom:1px solid var(--border);margin-bottom:6px}.switch{display:flex;align-items:center;gap:10px;border-top:1px solid var(--border);padding-top:10px;margin-top:8px}.switch input{display:none}.switch span,.toggle span{width:38px;height:22px;border-radius:999px;background:#C9C8DD;position:relative}.switch span:before,.toggle span:before{content:"";position:absolute;width:16px;height:16px;border-radius:50%;background:var(--ink-400);left:2px;top:3px}',
  '.exploreSplit{display:grid;grid-template-columns:minmax(0,3fr) minmax(0,2fr);gap:20px;align-items:stretch;height:calc(100vh - 190px);min-height:720px}.exploreLeft{display:flex;flex-direction:column;gap:20px;min-height:0}.leftTop{display:grid;grid-template-columns:220px minmax(0,1fr) minmax(0,1fr);gap:20px}.left{display:flex;flex-direction:column;gap:20px}.trend,.pricing,.market{display:flex;flex-direction:column;overflow:auto;min-height:0;height:100%}.trend h3,.pricing h3,.market h3{position:sticky;top:0;background:#fff;z-index:2;border-bottom:1px solid var(--border)}.pricing{flex:1;min-height:260px}.timeframe{padding-bottom:12px;overflow:visible}.timeframe label{display:flex;align-items:center;gap:10px;padding:10px 24px;font-size:13px;font-weight:650;color:var(--ink-600)}.timeframe label.selected{color:var(--blue-700);background:var(--muted-blue)}.stat{height:150px;padding:18px;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center}.stat span{font-weight:750;color:var(--ink-600)}.stat strong{font-size:30px;line-height:36px;font-weight:750;margin-top:18px}',
  'table{width:100%;border-collapse:collapse}th,td{border-top:1px solid var(--border);padding:13px 18px;text-align:left;vertical-align:top}th{background:rgba(243,242,255,.56);position:sticky;top:55px;z-index:1}td{font-size:13px;line-height:20px;color:var(--ink-600)}td:first-child{color:var(--ink-900);font-weight:650}.trend th:last-child,.pricing th:last-child,.trend td:last-child,.pricing td:last-child{text-align:right}.sortHeader{display:inline-flex;align-items:center;gap:6px;border:0;background:transparent;color:inherit;padding:0;font:inherit;text-transform:inherit;letter-spacing:inherit}.sortHeader span{font-size:11px;color:var(--ink-400)}.up,.price-fall{color:var(--green-700)!important}.down,.price-risk{color:var(--red-600)!important}.flat{color:var(--ink-400)!important}.price-warn{color:var(--orange-600)!important}.pricing p{padding:0 18px 14px;margin:-8px 0 0;color:var(--ink-400);font-size:12px;position:sticky;top:55px;background:#fff;z-index:2;border-bottom:1px solid var(--border)}.pricing th{top:91px}',
  '.market table{table-layout:fixed}.selectCol{width:42px;text-align:center}.statusCol{width:34px;text-align:center;color:var(--ink-400)}.market th:nth-child(3),.market td:nth-child(3){width:28%}.market th:nth-child(4),.market td:nth-child(4){width:48%}.market th:nth-child(5),.market td:nth-child(5){width:22%}.market a,.conceptName{color:var(--blue-500);font-weight:750}.market em,.conceptTable small{display:block;margin-top:4px;color:var(--ink-400);font-size:12px;font-style:normal}.rowSelected{background:var(--muted-blue)}.selectionBar,.bulkBar,.shortlistNotice{display:flex;align-items:center;gap:10px;padding:10px 14px;background:#F8F7FF;border-bottom:1px solid var(--border)}.selectionBar{position:sticky;top:55px;z-index:3}.selectionBar b,.bulkBar b{margin-right:auto;font-size:13px;font-weight:750}.selectionBar button,.bulkBar button,.shortlistNotice button{height:30px;border:1px solid var(--border-2);border-radius:7px;background:#fff;color:var(--ink-600);font-size:12px;font-weight:750;padding:0 10px}.selectionBar .primaryMini,.bulkBar .reportAction,.shortlistNotice button{border:0;background:var(--blue-500);color:#fff}.noticeActions{margin-left:auto;display:flex;gap:8px}.shortlistNotice{margin-bottom:14px;border:1px solid rgba(36,98,255,.18);border-radius:8px}.shortlistNotice .noticeClose{width:32px;background:#fff;color:var(--ink-600);border:1px solid rgba(36,98,255,.24)}.empty{min-height:420px;display:grid;place-items:center;color:var(--ink-600)}',
  '.conceptToolbar{display:flex;gap:12px;align-items:center;padding:14px;border-bottom:1px solid var(--border)}.conceptSearch{height:40px;flex:1;display:flex;align-items:center;gap:8px;padding:0 8px 0 12px}.conceptSearchClear{width:26px;height:26px;border:0;border-radius:999px;background:transparent;color:var(--ink-400);display:grid;place-items:center;padding:0}.bulkActions{display:flex;gap:8px}.bulkBar .reportAction{margin-left:auto;display:inline-flex;align-items:center;gap:8px;padding:0 14px}.conceptName{border:0;background:transparent;padding:0;text-align:left}.badge,.riskBadge,.drawerMeta span{display:inline-flex;align-items:center;height:24px;border-radius:999px;padding:0 9px;font-size:12px;font-weight:750}.statusDraft{background:var(--lavender-50);color:var(--ink-600)}.statusReview,.riskMedium{background:rgba(237,108,2,.12);color:var(--orange-600)}.statusReady,.riskLow{background:rgba(46,125,50,.10);color:var(--green-700)}.sourceBadge{background:var(--muted-blue);color:var(--blue-700)}.riskHigh{background:rgba(211,47,47,.10);color:var(--red-600)}',
  '.conceptDrawer{position:fixed;top:56px;right:0;bottom:0;width:430px;background:#fff;border-left:1px solid var(--border);box-shadow:-18px 0 40px rgba(39,39,45,.12);z-index:900;padding:20px;overflow:auto}.drawerHeader{display:flex;justify-content:space-between;gap:16px;border-bottom:1px solid var(--border);padding-bottom:16px;margin-bottom:16px}.drawerHeader h2{margin:4px 0 0;font-size:20px}.drawerHeader button{width:34px;height:34px;border:1px solid var(--border-2);border-radius:8px;background:#fff}.conceptDrawer label{display:block;margin:14px 0;font-size:13px;font-weight:750;color:var(--ink-600)}.conceptDrawer input,.conceptDrawer textarea,.field input,.field select{display:block;width:100%;margin-top:0;padding:10px 12px}.conceptDrawer textarea{min-height:110px;resize:vertical}.drawerMeta{display:flex;flex-wrap:wrap;gap:8px;margin:14px 0}.conceptDrawer footer,.configCard footer{display:flex;justify-content:flex-end;gap:10px;margin-top:28px;padding-top:24px;border-top:1px solid var(--border)}.primary{border:0!important;border-radius:8px!important;background:var(--blue-500)!important;color:white!important;font-weight:750!important;padding:10px 16px!important}',
  '.riskPage,.config{max-width:860px;margin:auto}.brief{padding:20px}.brief h2{display:flex;gap:8px;margin-top:0}.brief blockquote{border-left:3px solid var(--blue-500);margin:0 0 24px;padding:8px 14px;font-size:16px;line-height:28px;font-weight:750;background:rgba(243,242,255,.34)}.briefGrid{display:grid;grid-template-columns:1fr 1fr;gap:36px}.configCard{padding:28px 32px 30px}.configCard h2{padding:0;margin:0 0 26px}.configCard h3{margin:0 0 14px;font-size:16px}.configCard hr{border:0;border-top:1px solid var(--border);margin:28px 0 22px}.configGrid{display:grid;grid-template-columns:1fr 1fr;gap:22px 28px}.field span{display:block;font-size:13px;color:var(--ink-600);font-weight:750;margin-bottom:8px}.field input,.field select{height:48px}.toggle{display:flex;align-items:center;gap:10px;margin:12px 0}.toggle input{display:none}.toggle span{width:44px;height:24px}.toggle span:before{width:18px;height:18px;background:#fff}.toggle input:checked+span{background:var(--blue-500)}.toggle input:checked+span:before{left:23px}',
  '.loginPage{min-height:100vh;background:var(--blue-500);display:grid;place-items:center;padding:32px}.loginCard{width:min(450px,calc(100vw - 32px));background:#fff;border-radius:18px;overflow:hidden}.loginBody{padding:44px 42px 36px}.loginBody h2{text-align:center;color:var(--blue-500);font-size:30px;margin:0 0 34px}.loginBody h1{text-align:center;font-size:24px;margin:0 0 12px}.loginBody p{text-align:center;color:var(--ink-600);margin:0 0 32px}.loginBody form{display:flex;flex-direction:column;gap:20px}.loginBody label{font-weight:750;font-size:13px}.loginBody input:not([type=checkbox]){display:block;width:100%;height:52px;margin-top:8px;border:1px solid var(--border-2);border-radius:8px;padding:0 14px}.loginBody form>button{height:52px;border:0;border-radius:8px;background:var(--blue-500);color:#fff;font-weight:750}.loginRow{display:flex;justify-content:space-between;align-items:center}.loginRow label{display:flex;align-items:center;gap:8px;color:var(--ink-600)}.loginRow a{color:var(--blue-500);font-weight:750}.loginCard footer{display:flex;justify-content:space-between;align-items:center;background:#F8F7FF;border-top:1px solid var(--border);padding:26px 42px}.loginCard footer button{height:42px;border:1px solid var(--border-2);border-radius:8px;background:#fff;color:var(--blue-500);font-weight:750;padding:0 24px}',
  '@media(max-width:1200px){.filters{grid-template-columns:repeat(3,1fr)}.exploreSplit{grid-template-columns:1fr;height:auto;min-height:0}.leftTop{grid-template-columns:220px 1fr 1fr}.conceptDrawer{width:380px}}@media(max-width:980px){.leftTop{grid-template-columns:1fr}.exploreSplit{display:block}.conceptToolbar{flex-direction:column;align-items:stretch}.configGrid{grid-template-columns:1fr}}'
].join(String.fromCharCode(10));
